# Generated by Django 5.2 on 2025-06-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email'),
        ('accounts', '0007_user_groups_user_is_active_user_is_superuser_and_more'),
    ]

    operations = [
    ]
