# Generated by Django 5.2 on 2025-06-18 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название модуля')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('avg_rating', models.FloatField(blank=True, null=True, verbose_name='Общая оценка')),
                ('review_count', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('format', models.CharField(choices=[('TRADITIONAL', 'Традиционная'), ('ONLINE', 'Онлайн'), ('BLENDED', 'Смешанная')], max_length=11, verbose_name='Формат проведения')),
                ('control_type', models.CharField(choices=[('EXAM', 'Экзамен'), ('CREDIT', 'Зачет')], max_length=10, verbose_name='Тип контроля')),
                ('avg_interest', models.FloatField(default=None, null=True, verbose_name='Интересность дисциплины')),
                ('avg_complexity', models.FloatField(default=None, null=True, verbose_name='Уровень сложности')),
                ('avg_usefulness', models.FloatField(default=None, null=True, verbose_name='Полезность содержания')),
                ('is_usefulness_active', models.BooleanField(default=False)),
                ('avg_workload', models.FloatField(default=None, null=True, verbose_name='Объем нагрузки')),
                ('is_workload_active', models.BooleanField(default=False)),
                ('avg_logical_structure', models.FloatField(default=None, null=True, verbose_name='Логичность структуры')),
                ('is_logical_structure_active', models.BooleanField(default=False)),
                ('avg_practical_applicability', models.FloatField(default=None, null=True, verbose_name='Практическая применимость')),
                ('is_practical_applicability_active', models.BooleanField(default=False)),
                ('avg_teaching_effectiveness', models.FloatField(default=None, null=True, verbose_name='Эффективность преподавания')),
                ('is_teaching_effectiveness_active', models.BooleanField(default=False)),
                ('avg_materials_availability', models.FloatField(default=None, null=True, verbose_name='Доступность учебных материалов')),
                ('is_materials_availability_active', models.BooleanField(default=False)),
                ('avg_feedback_support', models.FloatField(default=None, null=True, verbose_name='Обратная связь и поддержка')),
                ('is_feedback_support_active', models.BooleanField(default=False)),
                ('description', models.TextField(verbose_name='Описание')),
                ('teachers', models.ManyToManyField(related_name='disciplines', to='disciplines.lecturer', verbose_name='Преподаватели')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplines', to='disciplines.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
    ]
