# Generated by Django 5.2 on 2025-05-05 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название дисциплины')),
                ('description', models.TextField(verbose_name='Описание дисциплины')),
                ('module', models.CharField(max_length=100, verbose_name='Модуль')),
                ('format', models.CharField(choices=[('TRADITIONAL', 'TRADITIONAL'), ('ONLINE', 'ONLINE'), ('BLENDED', 'BLENDED')], default='TRADITIONAL', max_length=11, verbose_name='Формат проведения')),
                ('avg_interest', models.FloatField(default=0, verbose_name='Интересность')),
                ('avg_complexity', models.FloatField(default=0, verbose_name='Сложность')),
                ('avg_usefulness', models.FloatField(default=0, verbose_name='Полезность')),
                ('avg_workload', models.FloatField(default=0, verbose_name='Нагрузка')),
                ('avg_practical_applicability', models.FloatField(default=0, verbose_name='Практическая применимость')),
                ('avg_logical_structure', models.FloatField(default=0, verbose_name='Логическая структура')),
                ('avg_teaching_effectiveness', models.FloatField(default=0, verbose_name='Эффективность преподавания')),
                ('avg_materials_availability', models.FloatField(default=0, verbose_name='Доступность материалов')),
                ('avg_feedback_support', models.FloatField(default=0, verbose_name='Обратная связь и поддержка')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('disciplines', models.ManyToManyField(related_name='lecturers', to='disciplines.discipline')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
