# Generated by Django 5.2 on 2025-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='disciplines',
        ),
        migrations.AddField(
            model_name='discipline',
            name='avg_rating',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Общая оценка'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='control_type',
            field=models.CharField(blank=True, choices=[('EXAM', 'Экзамен'), ('CREDIT', 'Зачет')], max_length=10, verbose_name='Тип контроля'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(related_name='disciplines', to='disciplines.lecturer', verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_complexity',
            field=models.FloatField(default=None, null=True, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_feedback_support',
            field=models.FloatField(default=None, null=True, verbose_name='Обратная связь и поддержка'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_interest',
            field=models.FloatField(default=None, null=True, verbose_name='Интересность дисциплины'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_logical_structure',
            field=models.FloatField(default=None, null=True, verbose_name='Логичность структуры'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_materials_availability',
            field=models.FloatField(default=None, null=True, verbose_name='Доступность учебных материалов'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_practical_applicability',
            field=models.FloatField(default=None, null=True, verbose_name='Практическая применимость'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_teaching_effectiveness',
            field=models.FloatField(default=None, null=True, verbose_name='Эффективность преподавания'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_usefulness',
            field=models.FloatField(default=None, null=True, verbose_name='Полезность содержания'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_workload',
            field=models.FloatField(default=None, null=True, verbose_name='Объем нагрузки'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='format',
            field=models.CharField(blank=True, choices=[('TRADITIONAL', 'Традиционная'), ('ONLINE', 'Онлайн'), ('BLENDED', 'Смешанная')], max_length=11, verbose_name='Формат проведения'),
        ),
    ]
