# Generated by Django 5.2 on 2025-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0002_remove_lecturer_disciplines_discipline_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая оценка'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='control_type',
            field=models.CharField(choices=[('EXAM', 'Экзамен'), ('CREDIT', 'Зачет')], max_length=10, verbose_name='Тип контроля'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='format',
            field=models.CharField(choices=[('TRADITIONAL', 'Традиционная'), ('ONLINE', 'Онлайн'), ('BLENDED', 'Смешанная')], max_length=11, verbose_name='Формат проведения'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
