# Generated by Django 5.2 on 2025-06-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0003_discipline_review_count_alter_discipline_avg_rating_and_more'),
        ('disciplines', '0003_module_alter_discipline_module'),
    ]

    operations = [
    ]
