# Generated by Django 5.2 on 2025-06-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0004_merge_20250609_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplines', to='disciplines.module', verbose_name='Модуль'),
        ),
    ]
