# Generated by Django 5.2 on 2025-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0005_alter_discipline_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='is_feedback_support_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_logical_structure_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_materials_availability_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_practical_applicability_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_teaching_effectiveness_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_usefulness_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_workload_active',
            field=models.BooleanField(default=False),
        ),
    ]
