# Generated by Django 5.2 on 2025-06-18 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest', models.PositiveSmallIntegerField(default=0, verbose_name='Интересность дисциплины')),
                ('is_interest_active', models.BooleanField(default=False, verbose_name='Учитывать интерес')),
                ('complexity', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень сложности')),
                ('is_complexity_active', models.BooleanField(default=False, verbose_name='Учитывать сложность')),
                ('usefulness', models.PositiveSmallIntegerField(default=0, verbose_name='Полезность содержания')),
                ('is_usefulness_active', models.BooleanField(default=False, verbose_name='Учитывать полезность')),
                ('workload', models.PositiveSmallIntegerField(default=0, verbose_name='Объем нагрузки')),
                ('is_workload_active', models.BooleanField(default=False, verbose_name='Учитывать нагрузку')),
                ('logical_structure', models.PositiveSmallIntegerField(default=0, verbose_name='Логичность структуры')),
                ('is_logical_structure_active', models.BooleanField(default=False, verbose_name='Учитывать логичность структуры')),
                ('practical_applicability', models.PositiveSmallIntegerField(default=0, verbose_name='Практическая применимость')),
                ('is_practical_applicability_active', models.BooleanField(default=False, verbose_name='Учитывать практическое применение')),
                ('teaching_effectiveness', models.PositiveSmallIntegerField(default=0, verbose_name='Эффективность преподавания')),
                ('is_teaching_effectiveness_active', models.BooleanField(default=False, verbose_name='Учитывать эффективность преподавания')),
                ('materials_availability', models.PositiveSmallIntegerField(default=0, verbose_name='Доступность учебных материалов')),
                ('is_materials_availability_active', models.BooleanField(default=False, verbose_name='Учитывать доступность учебных материалов')),
                ('feedback_support', models.PositiveSmallIntegerField(default=0, verbose_name='Обратная связь и поддержка')),
                ('is_feedback_support_active', models.BooleanField(default=False, verbose_name='Учитывать обратную связь и поддержку')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Анонимно')),
                ('avg_rating', models.FloatField(default=None, null=True, verbose_name='Общая оценка')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='disciplines.discipline', verbose_name='Дисциплина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
