# Generated by Django 5.2 on 2025-06-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_ai_evaluation_remove_review_complexity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='avg_complexity',
            field=models.FloatField(default=None, null=True, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='review',
            name='avg_feedback_support',
            field=models.FloatField(default=None, null=True, verbose_name='Обратная связь и поддержка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='avg_interest',
            field=models.FloatField(default=None, null=True, verbose_name='Интересность дисциплины'),
        ),
        migrations.AlterField(
            model_name='review',
            name='avg_logical_structure',
            field=models.FloatField(default=None, null=True, verbose_name='Логичность структуры'),
        ),
        migrations.AlterField(
            model_name='review',
            name='avg_materials_availability',
            field=models.FloatField(default=None, null=True, verbose_name='Доступность учебных материалов'),
        ),
        migrations.AlterField(
            model_name='review',
            name='avg_practical_applicability',
            field=models.FloatField(default=None, null=True, verbose_name='Практическая применимость'),
        ),
        migrations.AlterField(
            model_name='review',
            name='avg_teaching_effectiveness',
            field=models.FloatField(default=None, null=True, verbose_name='Эффективность преподавания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='avg_usefulness',
            field=models.FloatField(default=None, null=True, verbose_name='Полезность содержания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='avg_workload',
            field=models.FloatField(default=None, null=True, verbose_name='Объем нагрузки'),
        ),
    ]
