# Generated by Django 5.2 on 2025-06-13 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_avg_complexity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='is_deleted',
            new_name='anonymous',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avg_complexity',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avg_feedback_support',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avg_interest',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avg_logical_structure',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avg_materials_availability',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avg_practical_applicability',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avg_teaching_effectiveness',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avg_usefulness',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avg_workload',
        ),
        migrations.RemoveField(
            model_name='review',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='complexity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='feedback_support',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='interest',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='logical_structure',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='materials_availability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='practical_applicability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='teaching_effectiveness',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='usefulness',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='workload',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
