# Generated by Django 5.2 on 2025-06-14 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0006_discipline_is_feedback_support_active_and_more'),
        ('reviews', '0005_review_average_review_is_complexity_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='Анонимно'),
        ),
        migrations.AlterField(
            model_name='review',
            name='average',
            field=models.FloatField(default=None, null=True, verbose_name='Общая оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='complexity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='review',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='disciplines.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='review',
            name='feedback_support',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Обратная связь и поддержка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='interest',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Интересность дисциплины'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_complexity_active',
            field=models.BooleanField(default=False, verbose_name='Учитывать сложность'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_feedback_support_active',
            field=models.BooleanField(default=False, verbose_name='Учитывать обратную связь и поддержку'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_interest_active',
            field=models.BooleanField(default=False, verbose_name='Учитывать интерес'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_logical_structure_active',
            field=models.BooleanField(default=False, verbose_name='Учитывать логичность структуры'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_materials_availability_active',
            field=models.BooleanField(default=False, verbose_name='Учитывать доступность учебных материалов'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_practical_applicability_active',
            field=models.BooleanField(default=False, verbose_name='Учитывать практическое применение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_teaching_effectiveness_active',
            field=models.BooleanField(default=False, verbose_name='Учитывать эффективность преподавания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_usefulness_active',
            field=models.BooleanField(default=False, verbose_name='Учитывать полезность'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_workload_active',
            field=models.BooleanField(default=False, verbose_name='Учитывать нагрузку'),
        ),
        migrations.AlterField(
            model_name='review',
            name='logical_structure',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Логичность структуры'),
        ),
        migrations.AlterField(
            model_name='review',
            name='materials_availability',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Доступность учебных материалов'),
        ),
        migrations.AlterField(
            model_name='review',
            name='practical_applicability',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Практическая применимость'),
        ),
        migrations.AlterField(
            model_name='review',
            name='teaching_effectiveness',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Эффективность преподавания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='usefulness',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Полезность содержания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='workload',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Объем нагрузки'),
        ),
    ]
