# Generated by Django 5.2 on 2025-06-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_options_alter_review_anonymous_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='average',
            new_name='avg_rating',
        ),
    ]
